name: FNITE-API Recupero Sfide

on:
    schedule:
      - cron: '0 8 * * *'  # Esegui ogni giorno alle 10:00 orario italiano (09:00 UTC)
    workflow_dispatch:  # Permette di avviare manualmente il workflow

permissions: write-all

jobs:
  recupera_challenges:
    runs-on: ubuntu-latest
    steps:
      - name: Controlla il Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Configura Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Installa le dipendenze
        run: pip install requests

      - name: Salva Sfide
        run: python challenges.py
        env:
            API_KEY: ${{ secrets.API_KEY }}

      - name: Effettua commit e push
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git pull
          git add data/*
          git commit -m "Aggiorna Sfide" || echo "Nessuna modifica da salvare"
          git push
