name: FNITE-API Recupero Oggetti + GameplayTags 

on:
    schedule:
      - cron: '0 */3 * * *'  # Esegui ogni 3 ore
    workflow_dispatch:

permissions: write-all

jobs:
  recupera_api:
    runs-on: ubuntu-latest
    steps:
      - name: Controlla il Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Configura Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Installa le dipendenze
        run: pip install requests

      - name: Salva Oggetti + GTags
        run: python gtags.py
        env:
            API_KEY: ${{ secrets.API_KEY }}

      - name: Effettua commit e push
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git pull
          git add data/*
          git commit -m "Aggiorna Oggetti + GTags" || echo "Nessuna modifica da salvare"
          git push
